// Unit type definitions — stats from GDD v1.0
// Attack/Defense values = hit on d6 roll <= value

export const UNIT_TYPES = {
  // Land Units
  INFANTRY: {
    id: 'INFANTRY',
    name: 'Infantry',
    category: 'land',
    cost: 3,
    move: 1,
    attack: 1,
    defense: 2,
    special: 'Cheapest unit. +1 attack when paired with tank.',
    icon: '🚶',
  },
  TANK: {
    id: 'TANK',
    name: 'Tank',
    category: 'land',
    cost: 6,
    move: 3,
    attack: 3,
    defense: 3,
    special: 'Blitz: can pass through unoccupied territory.',
    icon: '🛡️',
  },
  THAAD: {
    id: 'THAAD',
    name: 'THAAD Battery',
    category: 'land',
    cost: 8,
    move: 0,
    attack: 0,
    defense: 0,
    special: 'Static. Intercepts nukes on 3 or less (d6).',
    icon: '📡',
  },

  // Air Units
  FIGHTER_F35: {
    id: 'FIGHTER_F35',
    name: 'F-35',
    category: 'air',
    cost: 10,
    move: 4,
    attack: 3,
    defense: 4,
    special: 'Coalition only. Air superiority.',
    factionRestriction: 'coalition',
    icon: '✈️',
  },
  FIGHTER_SU57: {
    id: 'FIGHTER_SU57',
    name: 'SU-57',
    category: 'air',
    cost: 9,
    move: 4,
    attack: 3,
    defense: 3,
    special: 'Alliance only. Slightly cheaper.',
    factionRestriction: 'alliance',
    icon: '✈️',
  },
  DRONE: {
    id: 'DRONE',
    name: 'Drone',
    category: 'air',
    cost: 4,
    move: 5,
    attack: 2,
    defense: 1,
    special: 'Cheap swarm unit. Can hit naval. Fragile.',
    icon: '🛸',
  },
  BOMBER: {
    id: 'BOMBER',
    name: 'Bomber',
    category: 'air',
    cost: 12,
    move: 6,
    attack: 4,
    defense: 1,
    special: 'Strategic bombing raids on factories.',
    icon: '💣',
  },
  NUCLEAR_BOMBER: {
    id: 'NUCLEAR_BOMBER',
    name: 'Nuclear Bomber',
    category: 'air',
    cost: 30,
    move: 8,
    attack: 0,
    defense: 1,
    special: 'Delivers nuclear payload. 3-round build time.',
    buildTime: 3,
    isNuclear: true,
    icon: '☢️',
  },

  // Naval Units
  DESTROYER: {
    id: 'DESTROYER',
    name: 'Destroyer',
    category: 'naval',
    cost: 8,
    move: 2,
    attack: 2,
    defense: 2,
    special: 'Can detect and attack submarines.',
    icon: '🚢',
  },
  CRUISER: {
    id: 'CRUISER',
    name: 'Cruiser',
    category: 'naval',
    cost: 12,
    move: 2,
    attack: 3,
    defense: 3,
    special: 'Shore bombardment (1 shot at 3 during amphibious).',
    icon: '🚢',
  },
  CARRIER: {
    id: 'CARRIER',
    name: 'Carrier',
    category: 'naval',
    cost: 16,
    move: 2,
    attack: 1,
    defense: 2,
    special: 'Carries up to 2 air units.',
    capacity: 2,
    icon: '🛳️',
  },
  SUBMARINE: {
    id: 'SUBMARINE',
    name: 'Submarine',
    category: 'naval',
    cost: 7,
    move: 2,
    attack: 2,
    defense: 1,
    special: 'First strike, can submerge to retreat.',
    icon: '🔱',
  },
  NUCLEAR_SUB: {
    id: 'NUCLEAR_SUB',
    name: 'Nuclear Sub',
    category: 'naval',
    cost: 25,
    move: 3,
    attack: 3,
    defense: 2,
    special: 'Delivers nuclear payload. 3-round build time.',
    buildTime: 3,
    isNuclear: true,
    icon: '☢️',
  },
  TRANSPORT: {
    id: 'TRANSPORT',
    name: 'Transport',
    category: 'naval',
    cost: 7,
    move: 2,
    attack: 0,
    defense: 0,
    special: 'Carries 1 tank OR 2 infantry. Defenseless.',
    capacity: { tank: 1, infantry: 2 },
    icon: '⛴️',
  },
};

// Helper: get available units for a player alliance
export const getAvailableUnits = (alliance) => {
  return Object.values(UNIT_TYPES).filter((unit) => {
    if (!unit.factionRestriction) return true;
    return unit.factionRestriction === alliance;
  });
};
